# Minimal Azure DevOps Pipeline - No template injection
# This is the most basic pipeline structure to avoid system-pre-steps.yml issues
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 1

- task: UseDotNet@2
  inputs:
    version: '8.0.x'
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'Restore and Build'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Publish Backend'
  inputs:
    command: 'publish'
    projects: 'AccountSalesApp.WebApp/AccountSalesApp.WebApp.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/backend'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/backend'
    artifactName: 'backend'
