trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Hello from Azure DevOps Pipeline"
      echo "Current directory: $(pwd)"
      ls -la
  displayName: 'Test Scripts'
